export const CREATE_NOTE = "CREATE_NOTE";
export const LOAD_NOTES_SUCCESS = "LOAD_NOTES_SUCCESS";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTES_STORE = "UPDATE_NOTES_STORE";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_NOTE_OPTIMISTIC = "DELETE_NOTE_OPTIMISTIC";
